---
version: "0.1"
globalTimeout: 90
testSuiteTimeout: 90
testSuiteStep: 90
runson: linux
autosplit: true
retryOnFailure: false
maxRetries: 5
concurrency: 2
pre:
  - sudo rm -rf /usr/bin/java
  - sudo ln -s /usr/lib/jvm/temurin-8-jdk-amd64/bin/java /usr/bin/java
  - npm install package.json
  - npm install karma
  - npm install karma-jasmine
  - npm install mocha
  - npm install karma-mocha-reporter
  - npm install karma-webdriver-launcher
  - npm fund
cacheKey: '{{ checksum "package-lock.json" }}'
cacheDirectories:
  - node_modules
testDiscovery:
  type: raw
  mode: dynamic
  command: grep -nri -l 'describe' test/*.js
testRunnerCommand: env KARMA_SPECS=$test ./node_modules/.bin/karma start karma.conf.js --single-run
