---
version: "0.1"
globalTimeout: 90
testSuiteTimeout: 90
testSuiteStep: 90
runson: mac
autosplit: true
retryOnFailure: true
maxRetries: 5
concurrency: 2
pre:
  - npm install package.json
  - npm install karma
  - npm install karma-jasmine
  - npm install mocha
  - npm install karma-mocha-reporter
  - npm install karma-webdriver-launcher
  - npm fund
cacheKey: '{{ checksum "package-lock.json" }}'
cacheDirectories:
  - node_modules
testDiscovery:
  type: raw
  mode: dynamic
  command: grep -nri -l 'describe' test/*.js
testRunnerCommand: env KARMA_SPECS="$test" ./node_modules/.bin/karma start karma.conf.js --single-run
